// UI contract test: all API responses are synthetic and intercepted in this browser only.
const { chromium } = require(process.argv[2] || 'playwright')
const assert = require('node:assert/strict')
;(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'})
 const page=await browser.newPage({viewport:{width:1440,height:1000}})
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 const points=Array.from({length:96},(_,i)=>({turbine_id:i<48?1:2,valid_at:new Date(Date.UTC(2026,0,30,20+i%48)).toISOString(),normalized_power:Math.round((.45+.25*Math.sin((i%48)/7))*1000)/1000,wind_speed_ms:6+(i%9)/2,temperature_c:-8+i%6}))
 const run={id:7,issued_at:'2026-01-31T00:00:00',weather_run_at:'2026-01-30T12:00:00',model_version:'TEST-FIXTURE',status:'complete',analysis:{source:'TEST FIXTURE — NOT REAL WEATHER'},points}
 let fail=false
 await page.route('http://127.0.0.1:8000/**',route=>{
   const path=new URL(route.request().url()).pathname
   route.fulfill({status:fail?409:200,contentType:'application/json',body:JSON.stringify(fail?{detail:'Train the model first'}:path==='/health'?{status:'ok'}:route.request().method()==='POST'?{id:7}:run)})
 })
 await page.goto('http://127.0.0.1:5173')
 await page.getByText('Начните с первого прогноза').waitFor()
 await page.screenshot({path:'tests/empty-desktop.png',fullPage:true})
 await page.getByRole('button',{name:/Запустить агента/}).click()
 await page.locator('tbody tr').nth(47).waitFor()
 assert.equal(await page.locator('tbody tr').count(),48)
 await page.getByRole('button',{name:'24 часа',exact:true}).click()
 assert.equal(await page.locator('tbody tr').count(),24)
 await page.locator('select').selectOption('2')
 await page.getByRole('button',{name:'Ветер',exact:true}).click()
 await page.getByRole('button',{name:'Температура',exact:true}).click()
 await page.getByRole('button',{name:'Мощность',exact:true}).click()
 await page.getByRole('button',{name:'48 часов',exact:true}).click()
 const download=page.waitForEvent('download');await page.getByRole('button',{name:/Экспорт CSV/}).click();assert.match((await download).suggestedFilename(),/turbine-2-48h/)
 await page.evaluate(()=>window.scrollTo(0,0))
 await page.screenshot({path:'tests/result-desktop.png',fullPage:true})
 await page.getByRole('button',{name:'Источники данных',exact:true}).click()
 await page.getByText('TEST-FIXTURE',{exact:true}).waitFor()
 await page.getByRole('button',{name:'История расчётов',exact:true}).click()
 await page.getByLabel('Открыть сохранённый прогноз по ID').fill('7')
 await page.getByRole('button',{name:'Открыть',exact:true}).click()
 await page.locator('tbody tr').nth(47).waitFor()
 await page.setViewportSize({width:390,height:844})
 await page.evaluate(()=>window.scrollTo(0,0))
 await page.screenshot({path:'tests/result-mobile.png',fullPage:true})
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Page should not overflow mobile viewport')
 fail=true;await page.getByRole('button',{name:/Запустить агента/}).click();await page.getByRole('alert').filter({hasText:'Сначала обучите модель'}).waitFor()
 assert.equal(await page.locator('tbody tr').count(),48,'Error preserves last result')
 assert.deepEqual(errors,[])
 await browser.close();console.log('PASS: empty/result, two turbines, horizons, chart tabs, export, provenance, lookup, mobile, server error; synthetic API only.')
})().catch(e=>{console.error(e);process.exit(1)})
