// UI contract test: all API responses are synthetic and intercepted in this browser only.
const { chromium } = require(process.argv[2] || 'playwright')
const assert = require('node:assert/strict')
;(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'})
 const page=await browser.newPage({viewport:{width:1440,height:1000}})
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 const points=Array.from({length:96},(_,i)=>({turbine_id:i<48?1:2,valid_at:new Date(Date.UTC(2026,0,30,20+i%48)).toISOString(),normalized_power:Math.round((.45+.25*Math.sin((i%48)/7))*1000)/1000,wind_speed_ms:6+(i%9)/2,temperature_c:-8+i%6}))
 const run={id:7,issued_at:'2026-01-31T00:00:00',weather_run_at:'2026-01-30T12:00:00',model_version:'TEST-FIXTURE',status:'complete',analysis:{source:'TEST FIXTURE — NOT REAL WEATHER'},points}
 const turbines=[{id:1,name:'Турбина 01',latitude:43.64515,longitude:78.535604},{id:2,name:'Турбина 02',latitude:43.643198,longitude:78.538828}]
 const models=[{id:1,version:'TEST-FIXTURE',validation_mae:.03,training_rows:1000,turbine_ids:[1,2]}]
 let fail=false,weatherFail=false
 let requireKey=false
 await page.route('https://maps.googleapis.com/**',route=>{
   const callback=new URL(route.request().url()).searchParams.get('callback')
   assert.equal(callback,'__windSightMapsReady','Map loader waits for the Google Maps callback')
   route.fulfill({status:200,contentType:'application/javascript',body:`window.google={maps:{MapTypeId:{TERRAIN:'terrain',ROADMAP:'roadmap',SATELLITE:'satellite'},LatLngBounds:class{extend(){}},Map:class{constructor(el,opts){el.dataset.mapReady='true';this.element=el;this.options=opts;this.zoom=opts.zoom;this.listeners={};window.__testMap=this}fitBounds(){}panTo(){}getZoom(){return this.zoom}getHeading(){return 0}addListener(name,fn){(this.listeners[name]??=[]).push(fn);return{remove(){}}}setZoom(zoom){this.zoom=zoom;(this.listeners.zoom_changed||[]).forEach(fn=>fn())}},InfoWindow:class{setContent(){}open(){}},importLibrary:async name=>name==='maps'?{Map:window.google.maps.Map,InfoWindow:window.google.maps.InfoWindow,LatLngBounds:window.google.maps.LatLngBounds,MapTypeId:window.google.maps.MapTypeId}:{AdvancedMarkerElement:class{constructor(opts){Object.assign(this,opts);opts.map.element.append(opts.content)}addEventListener(){}},PinElement:class{constructor(){this.element=document.createElement('div')}}}}};window[${JSON.stringify(callback)}]()`})
 })
 await page.route('https://single-runs-api.open-meteo.com/**',route=>{
   const url=new URL(route.request().url())
   assert.equal(url.searchParams.get('models'),'ecmwf_ifs')
   assert.equal(url.searchParams.get('hourly'),'wind_speed_100m,wind_direction_100m')
   const start=Date.parse(url.searchParams.get('run')+'Z')
   const payload={hourly_units:{wind_speed_100m:'m/s',wind_direction_100m:'°'},hourly:{
     time:Array.from({length:96},(_,i)=>new Date(start+i*3600000).toISOString().slice(0,16)),
     wind_speed_100m:Array.from({length:96},(_,i)=>5+i/10),
     wind_direction_100m:Array(96).fill(90)
   }}
   route.fulfill({status:weatherFail?503:200,contentType:'application/json',body:JSON.stringify(weatherFail?{error:true,reason:'Fixture outage'}:payload)})
 })
 await page.route('http://127.0.0.1:8000/**',route=>{
   const path=new URL(route.request().url()).pathname
   if(requireKey&&route.request().method()==='POST')assert.equal(route.request().headers()['x-admin-key'],'TEST-OPERATOR-KEY')
   const newTurbine=path==='/turbines'&&route.request().method()==='POST'?{id:3,...route.request().postDataJSON()}:null
   if(newTurbine)turbines.push(newTurbine)
   const payload=path==='/health'?{status:'ok'}:newTurbine||path==='/turbines'?newTurbine||turbines:path==='/models'?models:path==='/forecasts'?[{id:7,issued_at:run.issued_at,status:'complete',point_count:96}]:path.startsWith('/measurements/upload')?{rows:1,imported:1,skipped:0}:path==='/models/train'?{revision_id:1,model_version:'TEST-FIXTURE',validation_mae:.03,warning:''}:route.request().method()==='POST'?{id:7}:run
   route.fulfill({status:fail&&path.startsWith('/forecasts/')&&route.request().method()==='POST'?409:200,contentType:'application/json',body:JSON.stringify(fail&&path.startsWith('/forecasts/')&&route.request().method()==='POST'?{detail:'Train the model first'}:payload)})
 })
 await page.goto('http://127.0.0.1:5173')
 assert.equal(await page.title(),'Wind Power Forecasting · Прогнозирование ветровой генерации')
 assert.equal(await page.locator('.brand').getAttribute('aria-label'),'Wind Power Forecasting — обзор прогноза')
 assert.match(await page.locator('.brand-name').innerText(),/Wind Power\s+Forecasting\s+Команда HEALTH CORE/)
 assert.ok(await page.locator('.brand-mark').evaluate(img=>img.complete&&img.naturalWidth>0),'Project mark loads')
 await page.getByText('Начните с первого прогноза').waitFor()
 await page.getByRole('button',{name:'Свернуть панель',exact:true}).click()
 assert.equal(await page.getByRole('button',{name:'Развернуть панель',exact:true}).getAttribute('aria-expanded'),'false')
 for(const label of ['Прогноз','История','Источники','Данные']) assert.ok(await page.locator('.nav-text').getByText(label,{exact:true}).isVisible())
 await page.reload()
 await page.getByRole('button',{name:'Развернуть панель',exact:true}).waitFor()
 assert.ok(await page.locator('.shell').evaluate(el=>el.classList.contains('sidebar-collapsed')),'Collapsed preference survives reload')
 await page.getByRole('button',{name:'Развернуть панель',exact:true}).click()
 assert.equal(await page.getByRole('button',{name:'Свернуть панель',exact:true}).getAttribute('aria-expanded'),'true')
 await page.screenshot({path:'tests/empty-desktop.png',fullPage:true})
 await page.getByRole('button',{name:/Запустить агента/}).click()
 await page.locator('tbody tr').nth(47).waitFor()
 for(const width of [1440,1280,1024,768,390]){
   await page.setViewportSize({width,height:900})
   for(const collapsed of [false,true]){
     const isCollapsed=await page.locator('.shell').evaluate(el=>el.classList.contains('sidebar-collapsed'))
     if(isCollapsed!==collapsed)await page.locator('.sidebar-toggle').click()
     assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`No page overflow at ${width}, collapsed=${collapsed}`)
     const nav=await page.locator('.nav-text').evaluateAll(els=>els.map(el=>({visible:el.getBoundingClientRect().width>0,fits:el.scrollWidth<=el.clientWidth+1})))
     assert.ok(nav.every(n=>n.visible&&n.fits),`Nav labels visible at ${width}, collapsed=${collapsed}`)
     const inputSize=await page.locator('.controls input').evaluate(el=>parseFloat(getComputedStyle(el).fontSize))
     assert.ok(inputSize>=16)
     const cellSize=await page.locator('tbody td').first().evaluate(el=>parseFloat(getComputedStyle(el).fontSize))
     assert.ok(cellSize>=15)
     await page.evaluate(()=>window.scrollTo(0,0))
     await page.screenshot({path:`tests/layout-${width}-${collapsed?'collapsed':'expanded'}.png`,fullPage:true})
   }
 }
 await page.setViewportSize({width:1440,height:1000})
 await page.getByRole('button',{name:'Развернуть панель',exact:true}).click()
 assert.equal(await page.locator('tbody tr').count(),48)
 await page.getByRole('button',{name:'24 часа',exact:true}).click()
 assert.equal(await page.locator('tbody tr').count(),24)
 await page.locator('.controls select').first().selectOption('2')
 await page.getByRole('button',{name:'Ветер',exact:true}).click()
 await page.getByRole('button',{name:'Температура',exact:true}).click()
 await page.getByRole('button',{name:'Мощность',exact:true}).click()
 await page.getByRole('button',{name:'48 часов',exact:true}).click()
 const download=page.waitForEvent('download');await page.getByRole('button',{name:/Экспорт CSV/}).click();assert.match((await download).suggestedFilename(),/turbine-2-48h/)
 await page.evaluate(()=>window.scrollTo(0,0))
 await page.screenshot({path:'tests/result-desktop.png',fullPage:true})
 await page.getByRole('button',{name:'Источники данных',exact:true}).click()
 await page.getByText('TEST-FIXTURE',{exact:true}).waitFor()
 await page.getByRole('button',{name:'История расчётов',exact:true}).click()
 await page.getByText('1 в БД',{exact:true}).waitFor()
 await page.getByRole('button',{name:/#7 .*96 точек/}).waitFor()
 await page.getByLabel('Открыть сохранённый прогноз по ID').fill('7')
 await page.getByRole('button',{name:'Открыть',exact:true}).click()
 await page.locator('tbody tr').nth(47).waitFor()
 await page.getByRole('button',{name:'География ВЭС',exact:true}).click()
 await page.getByRole('heading',{name:'География ВЭС',exact:true,level:1}).waitFor()
 assert.equal(await page.locator('.geo-turbine').count(),2,'Both backend turbine coordinates are listed')
 await page.locator('.geo-wind-badge:not([hidden])').first().waitFor()
 assert.equal(await page.locator('.geo-wind-badge:not([hidden])').count(),2,'Wind vectors appear at both turbines')
 assert.match(await page.locator('.geo-wind-badge').first().innerText(),/5,8 м\/с/)
 assert.equal(await page.locator('.geo-wind-arrow').first().evaluate(el=>el.style.transform),'rotate(270deg)','A wind from east flows west')
 await page.evaluate(()=>window.__testMap.setZoom(14))
 assert.equal(await page.locator('.geo-wind-badge').nth(1).evaluate(el=>el.style.bottom),'-47px','Labels separate at low zoom')
 await page.evaluate(()=>window.__testMap.setZoom(17))
 assert.equal(await page.locator('.geo-wind-badge').nth(1).evaluate(el=>el.style.bottom),'52px','Labels return near turbine pins on zoom in')
 await page.locator('.geo-wind-timeline input').evaluate(el=>{el.value='2';el.dispatchEvent(new Event('input',{bubbles:true}))})
 assert.match(await page.locator('.geo-wind-badge').first().innerText(),/5,9 м\/с/,'Time slider updates the map data')
 await page.getByRole('button',{name:'Слой ветра: включён'}).click()
 assert.equal(await page.locator('.geo-wind-badge:not([hidden])').count(),0,'Layer can be hidden')
 await page.getByRole('button',{name:'Слой ветра: выключен'}).click()
 assert.equal(await page.locator('.geo-wind-badge:not([hidden])').count(),2,'Layer can be restored')
 await page.locator('.geo-wind-date input').fill('2026-02-01')
 await page.getByText(/Выпуск погоды: 2026-01-31 12:00 UTC/).waitFor()
 await page.locator('.geo-wind-badge:not([hidden])').first().waitFor()
 weatherFail=true
 await page.locator('.geo-wind-date input').fill('2026-02-02')
 await page.getByRole('alert').filter({hasText:'Слой ветра недоступен'}).waitFor()
 assert.equal(await page.locator('.geo-turbine').count(),2,'Weather outage does not hide the map or turbines')
 weatherFail=false
 await page.getByRole('button',{name:'Повторить'}).click()
 await page.locator('.geo-wind-badge:not([hidden])').first().waitFor()
 assert.equal(await page.locator('.geo-map').getAttribute('data-map-ready'),'true','Map initializes after the API callback')
 assert.equal(await page.getByRole('alert').count(),0,'Geography does not report a loader error')
 assert.equal(await page.locator('.geo-map').evaluate(el=>el.style.height || getComputedStyle(el).minHeight),'560px','Terrain map has a usable desktop height')
 await page.screenshot({path:'tests/geography-desktop.png',fullPage:true})
 await page.setViewportSize({width:390,height:844})
 await page.evaluate(()=>window.scrollTo(0,0))
 await page.screenshot({path:'tests/result-mobile.png',fullPage:true})
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Page should not overflow mobile viewport')
 await page.getByRole('button',{name:'Данные и модели',exact:true}).click()
 await page.getByText('Загрузка обучающих данных',{exact:true}).waitFor()
 await page.getByText('TEST-FIXTURE',{exact:true}).waitFor()
 await page.getByRole('textbox',{name:'Ключ оператора для создания и расчёта'}).fill('TEST-OPERATOR-KEY')
 requireKey=true
 await page.getByRole('textbox',{name:'Название'}).fill('Турбина 03')
 await page.getByRole('spinbutton',{name:'Широта'}).fill('43.7')
 await page.getByRole('spinbutton',{name:'Долгота'}).fill('78.6')
 await page.getByRole('button',{name:'Сохранить турбину'}).click()
 await page.getByText(/Добавлена турбина Турбина 03/).waitFor()
 assert.equal(await page.locator('.manage-card').last().getByText('Турбина 03',{exact:true}).count(),1)
 await page.locator('input[type=file]').setInputFiles({name:'train.csv',mimeType:'text/csv',buffer:Buffer.from('ID,Статистическое время,Средняя скорость ветра(m/s),Нормализованная активная мощность,Средняя температура окружающей среды(°C)\n1,2023-03-11 0:00:00,6.73,0.39,15.38\n')})
 await page.getByRole('button',{name:'Загрузить CSV',exact:true}).click()
 await page.getByText(/Проверено 1 строк/).waitFor()
 await page.getByRole('button',{name:'Обучить новую ревизию'}).click()
 await page.getByText(/Обучена ревизия TEST-FIXTURE/).waitFor()
 await page.getByRole('button',{name:'Обзор прогноза',exact:true}).click()
 fail=true;await page.getByRole('button',{name:/Запустить агента/}).click();await page.getByRole('alert').filter({hasText:'Сначала обучите модель'}).waitFor()
 assert.equal(await page.locator('tbody tr').count(),48,'Error preserves last result')
 assert.deepEqual(errors,[])
 await browser.close();console.log('PASS: forecast flows, wind overlay/time/zoom/date controls, navigation, export, provenance, lookup, mobile, server error; synthetic API only.')
})().catch(e=>{console.error(e);process.exit(1)})
